BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: '7'
            font_size: 48
            multiline: False
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: "Up"
            Button:
                text: "Down"
    Button:
        text: 'Covert m to km'
    Label:
        text: 'Layout test'
